apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-virtual-machines"
spec:
  title: "Virtual Machines"
  description: "Overview of provisioning virtual machines."
  duration: 30m
  workshop:
    files:
    - image:
        url: "$(image_repository)/labs-educates-showcase-files:latest"
      includePaths:
        - /workshops/lab-virtual-machines/resources/**
        - /workshops/lab-virtual-machines/workshop/**
      newRootPath: workshops/lab-virtual-machines
  session:
    namespaces:
      budget: large
    applications:
      terminal:
        enabled: true
        layout: split
      examiner:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: vmi-viewer
      rules:
      - apiGroups:
        - kubevirt.io
        resources:
        - virtualmachines
        - virtualmachineinstances
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - subresources.kubevirt.io
        resources:
        - virtualmachineinstances/console
        - virtualmachineinstances/filesystemlist
        - virtualmachineinstances/userlist
        verbs:
        - get
      - apiGroups:
        - subresources.kubevirt.io
        resources:
        - virtualmachines/restart
        verbs:
        - update
      - apiGroups:
        - subresources.kubevirt.io
        resources:
        - virtualmachineinstances/softreboot
        verbs:
        - update
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: vmi-viewer
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: vmi-viewer
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-datavolume-clone
        namespace: $(workshop_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: datavolume-clone
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: secrets.educates.dev/v1beta1
      kind: SecretCopier
      metadata:
        name: $(session_namespace)-ssh-keys
      spec:
        rules:
        - sourceSecret:
            name: $(ssh_keys_secret)
            namespace: $(workshop_namespace)
          targetNamespaces:
            nameSelector:
              matchNames:
              - $(session_namespace)
          targetSecret:
            name: ssh-keys
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm-01
      spec:
        source:
          pvc:
            namespace: $(workshop_namespace)
            name: ubuntu-22-04
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    - apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      metadata:
        name: vm-01
        labels:
          kubevirt.io/vm: vm-01
      spec:
        running: true
        template:
          metadata:
            labels:
              kubevirt.io/vm: vm-01
          spec:
            terminationGracePeriodSeconds: 30
            accessCredentials:
            - sshPublicKey:
                source:
                  secret:
                    secretName: ssh-keys
                propagationMethod:
                  configDrive: {}
            domain:
              cpu:
                cores: 2
              resources:
                limits:
                  memory: 2Gi
                requests:
                  memory: 2Gi
              devices:
                disks:
                - name: disk1
                  disk:
                    bus: virtio
                - disk:
                    bus: virtio
                  name: cloudinitdisk
                interfaces:
                - name: default
                  masquerade: {}
            networks:
            - name: default
              pod: {}
            volumes:
            - name: disk1
              dataVolume:
                name: vm-01
            - name: cloudinitdisk
              cloudInitConfigDrive:
                userData: |-
                  #cloud-config
                  password: $(services_password)
                  chpasswd: { expire: False }
                  runcmd:
                  - echo "set enable-bracketed-paste off" >> /etc/inputrc
    - apiVersion: v1
      kind: Service
      metadata:
        name: vm-01
      spec:
        selector:
          kubevirt.io/vm: vm-01
        ports:
          - name: ssh
            protocol: TCP
            port: 22
            targetPort: 22
  environment:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: datavolume-clone
      rules:
      - apiGroups:
        - kubevirt.io
        resources:
        - datavolume/source
        verbs:
        - get
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ubuntu-22-04
      spec:
        source:
          registry:
            url: "docker://quay.io/containerdisks/ubuntu:22.04"
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
