apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-shared-resources"
spec:
  title: "Shared Resources"
  description: "Overview of pre-creating shared resources."
  duration: 30m
  workshop:
    files:
    - image:
        url: "$(image_repository)/labs-educates-showcase-files:latest"
      includePaths:
        - /workshops/lab-shared-resources/resources/**
        - /workshops/lab-shared-resources/workshop/**
      newRootPath: workshops/lab-shared-resources
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: false
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
