apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-java-environment"
spec:
  title: "Java Environment"
  description: "Overview of working on Java applications."
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: "$(image_repository)/labs-educates-showcase-files:latest"
      includePaths:
        - /workshops/lab-java-environment/resources/**
        - /workshops/lab-java-environment/workshop/**
      newRootPath: workshops/lab-java-environment
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
