apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: labs-educates-showcase
spec:
  portal:
    title: Educates Showcase
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 1
    workshop:
      defaults:
        reserved: 1
        initial: 0
        expires: 30m
        overtime: 10m
        deadline: 60m
        orphaned: 5m
  workshops:
  - name: lab-workshop-session
  - name: lab-session-namespace  
  - name: lab-virtual-cluster
  #- name: lab-virtual-machines
  - name: lab-integrated-editor
  - name: lab-slide-presentations
  - name: lab-docker-runtime
  - name: lab-examiner-scripts
  - name: lab-java-environment
  - name: lab-conda-environment
  - name: lab-shared-resources
  - name: lab-session-resources
  - name: lab-extension-packages
