apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-integrated-editor"
spec:
  title: "Integrated Editor"
  description: "Overview of integrated VS Code editor."
  duration: 30m
  workshop:
    files:
    - image:
        url: "$(image_repository)/labs-educates-showcase-files:latest"
      includePaths:
        - /workshops/lab-integrated-editor/resources/**
        - /workshops/lab-integrated-editor/workshop/**
      newRootPath: workshops/lab-integrated-editor
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
