apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-examiner-scripts"
spec:
  title: "Examiner Scripts"
  description: "Overview of using self check examinations."
  duration: 30m
  workshop:
    files:
    - image:
        url: "$(image_repository)/labs-educates-showcase-files:latest"
      includePaths:
        - /workshops/lab-examiner-scripts/resources/**
        - /workshops/lab-examiner-scripts/workshop/**
      newRootPath: workshops/lab-examiner-scripts
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      examiner:
        enabled: true
