apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  type: ClusterIP
  selector:
    app: blog
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
